"""price_inquiry 包 — 智能询价节点（拆包后的兼容入口）。

对外符号与拆包前完全一致，外部代码继续使用
`from agent.nodes.price_inquiry import ...` 无需任何改动。
"""

from .db import (
    _CLEAN_DB,
    _get_connection,
    _get_settings,
    _mysql_base_kwargs,
    _pool_connections,
    _pool_in_use,
    _pool_lock,
    _release_connection,
    _settings_cache,
)
from .db_async import (
    _build_pool,
    _get_pool,
    acquire,
    close_pool,
    health_check,
)


from .enum_norm import (
    _ENUM_CACHE,
    _ENUM_CACHE_LOCK,
    _LEVEL_SCALE_CHARS,
    _load_enum_values,
    _match_company_levels,
    _match_enum_value,
    _normalize_intent_enums,
)

from .intent import (
    _CODE_TOKEN_PATTERN,
    _COMPANY_NAME_MAX_LEN,
    _COMPANY_NAME_MIN_LEN,
    _COMPANY_NAME_SUFFIXES,
    _ENTITY_SUFFIXES,
    _INTENT_NOISE_WORDS,
    _OVERLONG_KEYWORD_LIMIT,
    _PROJECT_NUMBER_RE,
    _QUERY_FILLER_PATTERN,
    _UNIFIED_INTENT_PROMPT,
    _UNIFIED_INTENT_SYSTEM,
    _build_llm,
    _dedupe_keep_order,
    _denoise_keywords,
    _extract_json,
    _extract_keywords,
    _extract_project_number_candidate,
    _is_valid_company_name,
    _looks_like_code,
    _normalize_token,
    _parse_unified_intent,
    _parse_unified_intent_async,
    _post_process_intent,
    _safe_parse_intent,
    _split_overlong_keyword,
)

from .models import (
    HardFilters,
    SearchIntent,
)

from .node import (
    _QUERY_INTENT_KEYWORDS,
    _SUB_ROUTE_MAP,
    _UNIFIED_GUIDANCE_TEXT,
    _build_capability_boundary_answer,
    _build_unified_guidance,
    _get_query_fn,
    _has_valid_query_entity,
    node_price_inquiry,
)

from .node_async import (
    node_price_inquiry_async,
)

from .queries import (
    _query_all_tables,
    _query_bidding_aggregation,
    _query_bidding_data,
    _query_company_data,
    _query_penalty_by_company_name,
)

from .recall_async import (
    _SQLTimeoutError,
    _merge_and_rank,
    _query_table_async,
    query_tables_async,
    safe_execute,
)

from .recall import (
    _RECALL_STAGE_WEIGHTS,
    _clean_result_row,
    _enrich_rows_full_columns,
    _execute_recall_chain_core,
    _execute_recall_chain_for_table,
    _execute_sql_fetch_rows,
    _execute_sql_with_timeout,
    _hybrid_score,
    _log_recall_funnel,
    _merge_result_record,
    _profile_execute,
    _query_tables,
    _rank_records,
    _sql_executor,
)

from .schema import (
    _HARDCODED_SCHEMA,
    _get_classification,
)

from .sql_builders import (
    _PREFERENCE_FILTER_FIELDS,
    _build_candidate_sql,
    _build_constraint_conditions,
    _build_full_scan_sql,
    _build_fulltext_expression,
    _build_hard_conditions_extended,
    _build_like_fallback_sql,
    _build_order_clause,
    _build_preference_conditions,
    _build_search_term,
    _has_preference_filters,
    _strip_preference_filters,
)

__all__ = [
    "HardFilters",
    "SearchIntent",
    "_CLEAN_DB",
    "_CODE_TOKEN_PATTERN",
    "_COMPANY_NAME_MAX_LEN",
    "_COMPANY_NAME_MIN_LEN",
    "_COMPANY_NAME_SUFFIXES",
    "_ENTITY_SUFFIXES",
    "_ENUM_CACHE",
    "_ENUM_CACHE_LOCK",
    "_HARDCODED_SCHEMA",
    "_INTENT_NOISE_WORDS",
    "_LEVEL_SCALE_CHARS",
    "_OVERLONG_KEYWORD_LIMIT",
    "_PREFERENCE_FILTER_FIELDS",
    "_PROJECT_NUMBER_RE",
    "_QUERY_FILLER_PATTERN",
    "_QUERY_INTENT_KEYWORDS",
    "_RECALL_STAGE_WEIGHTS",
    "_SUB_ROUTE_MAP",
    "_UNIFIED_GUIDANCE_TEXT",
    "_UNIFIED_INTENT_PROMPT",
    "_UNIFIED_INTENT_SYSTEM",
    "_build_candidate_sql",
    "_build_capability_boundary_answer",
    "_build_constraint_conditions",
    "_build_full_scan_sql",
    "_build_fulltext_expression",
    "_build_hard_conditions_extended",
    "_build_like_fallback_sql",
    "_build_llm",
    "_build_order_clause",
    "_build_preference_conditions",
    "_build_search_term",
    "_build_unified_guidance",
    "_clean_result_row",
    "_dedupe_keep_order",
    "_denoise_keywords",
    "_enrich_rows_full_columns",
    "_execute_recall_chain_core",
    "_execute_recall_chain_for_table",
    "_execute_sql_fetch_rows",
    "_execute_sql_with_timeout",
    "_extract_json",
    "_extract_keywords",
    "_extract_project_number_candidate",
    "_get_classification",
    "_get_connection",
    "_get_query_fn",
    "_get_settings",
    "_has_preference_filters",
    "_has_valid_query_entity",
    "_hybrid_score",
    "_is_valid_company_name",
    "_load_enum_values",
    "_log_recall_funnel",
    "_looks_like_code",
    "_match_company_levels",
    "_match_enum_value",
    "_merge_result_record",
    "_mysql_base_kwargs",
    "_normalize_intent_enums",
    "_normalize_token",
    "_SQLTimeoutError",
    "_build_pool",
    "_get_pool",
    "_merge_and_rank",
    "_parse_unified_intent",
    "_parse_unified_intent_async",
    "_pool_connections",
    "_pool_in_use",
    "_pool_lock",
    "_post_process_intent",
    "_profile_execute",
    "_query_all_tables",
    "_query_bidding_aggregation",
    "_query_bidding_data",
    "_query_company_data",
    "_query_penalty_by_company_name",
    "_query_table_async",
    "_query_tables",
    "_rank_records",
    "_release_connection",
    "_safe_parse_intent",
    "_settings_cache",
    "_split_overlong_keyword",
    "_sql_executor",
    "_strip_preference_filters",
    "acquire",
    "close_pool",
    "health_check",
    "node_price_inquiry",
    "node_price_inquiry_async",
    "query_tables_async",
    "safe_execute",
]
